import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import Head from "./header/head/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Shawarma Stop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} h-full overflow-x-hidden antialiased`}
    >
      <body className="flex min-h-full w-full min-w-0 flex-col overflow-x-hidden">
        <CartProvider>
          <main className="min-w-0 w-full max-w-full flex-grow">
            <Head />
            {children}
            </main>
        </CartProvider>
      </body>
    </html>
  );
}